// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ActivityID uuid.UUID
	Name       string
	Points     int32
	CreatedAt  time.Time
}

type ActivityLog struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ActivityID          uuid.UUID
	Duration            int32
	Points              int32
	LoggedAt            time.Time
	ActivityDescription string
}

type AllActivity struct {
	ID   uuid.UUID
	Type string
}

type CustomActivity struct {
	ActivityID uuid.UUID
	UserID     uuid.UUID
	Name       string
	Points     int32
	CreatedAt  time.Time
}

type SuggestFeature struct {
	ID          uuid.UUID
	Title       string
	Description string
	Username    string
	Upvote      int32
}

type Team struct {
	ID           uuid.UUID
	Name         string
	TeamIndustry string
	TeamSize     int32
	IsPrivate    bool
	CreatedBy    uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type TeamActivity struct {
	ID            uuid.UUID
	TeamID        uuid.UUID
	ActivityName  string
	Points        int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ActivityRoles []string
}

type TeamActivityLog struct {
	ID           uuid.UUID
	TeamID       uuid.UUID
	UserID       uuid.UUID
	ActivityName string
	Points       int32
	LoggedAt     time.Time
}

type TeamActivityRequest struct {
	ID           uuid.UUID
	TeamID       uuid.UUID
	UserID       uuid.UUID
	ActivityName string
	Points       int32
	CreatedAt    time.Time
}

type TeamInvitation struct {
	ID          uuid.UUID
	TeamID      uuid.UUID
	SenderID    uuid.UUID
	RecipientID uuid.UUID
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Seen        bool
}

type TeamMembership struct {
	ID        uuid.UUID
	TeamID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamRole struct {
	ID       uuid.UUID
	RoleName string
	TeamID   uuid.UUID
}

type TeamUserRole struct {
	ID               uuid.UUID
	TeamMembershipID uuid.UUID
	RoleID           uuid.UUID
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Username     string
	Email        string
	PasswordHash sql.NullString
	GoogleID     sql.NullString
}

type UserActivity struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	Points       int32
	ActivityType interface{}
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserActivityLog struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	ActivityID          uuid.NullUUID
	Duration            int32
	Points              int32
	ActivityDescription string
	LoggedAt            time.Time
}

type UserGoal struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	GoalDate   time.Time
	GoalPoints int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Status     string
}
